//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet
    {
        public int IdChitiet { get; set; }
        public string BoNho { get; set; }
        public string Ram { get; set; }
        public string CPU { get; set; }
        public string manhinh { get; set; }
        public string camera { get; set; }
        public string HĐH { get; set; }
        public string Sim { get; set; }
        public string pin { get; set; }
        public Nullable<int> IdDT { get; set; }
    
        public virtual DienThoai DienThoai { get; set; }
    }
}
