//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class DienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DienThoai()
        {
            this.ChiTiets = new HashSet<ChiTiet>();
            this.HoaDons = new HashSet<HoaDon>();
            hinh1 = "~/Content/Image/dienthoai1.jpg";
            hinh2 = "~/Content/Image/dienthoai2.jpg";
            hinh3 = "~/Content/Image/dienthoai3.jpg";
        }

        public int IdDT { get; set; }
        public string TenDT { get; set; }
        public string Mota { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Gia { get; set; }
        public string hinh1 { get; set; }
        public string mau1 { get; set; }
        public string hinh2 { get; set; }
        public string mau2 { get; set; }
        public string hinh3 { get; set; }
        public string mau3 { get; set; }
        public string ChiTiet { get; set; }
        public string idHang { get; set; }
        public Nullable<int> IdLich { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet> ChiTiets { get; set; }
        public virtual Hang Hang { get; set; }
        public virtual LichNhap LichNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage3 { get; set; }
    }
}