//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int IdKH { get; set; }
        public string tenKH { get; set; }
        public string diachi { get; set; }
        public string sđt { get; set; }
        public string Taikhoan { get; set; }
        public string MatKhau { get; set; }
    }
}
