//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class KhuyenMai
    {
        public KhuyenMai()
        {
            HinhAnh = "~/Content/Image/anhkm1.jpg";
        }
        public int IdKM { get; set; }
        public string MaKM { get; set; }
        public string ChiTiet { get; set; }
        public string HinhThucGiam { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> SoLuongConLai { get; set; }
        public string TinhTrang { get; set; }
        public string HinhAnh { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}