//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMua()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int IdPM { get; set; }
        public string Email { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string KhuyenMai { get; set; }
        public string DiaChi { get; set; }
        public string Ghichu { get; set; }
        public string TinhTrang { get; set; }
        public string SĐT { get; set; }
        public string HThuc { get; set; }
        public string Mau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
